import hashlib
import json
import os
import secrets
import sqlite3
import time
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterator


AUTH_DATABASE_PATH = Path(__file__).resolve().with_name("auth.sqlite3")
SESSION_TTL_SECONDS = 8 * 60 * 60
PASSWORD_RESET_TTL_SECONDS = 30 * 60
OAUTH_STATE_TTL_SECONDS = 10 * 60
EMAIL_DRAFT_TTL_SECONDS = 10 * 60


class _ConnectionAdapter:
    def __init__(self, connection: Any, postgres: bool) -> None:
        self._connection = connection
        self.is_postgres = postgres

    def execute(self, query: str, parameters: tuple[object, ...] = ()) -> Any:
        if self.is_postgres:
            query = query.replace("?", "%s")
        return self._connection.execute(query, parameters)

    def executescript(self, script: str) -> None:
        self._connection.executescript(script)


@contextmanager
def _connection() -> Iterator[_ConnectionAdapter]:
    database_url = os.getenv("DATABASE_URL")
    is_vercel = os.getenv("VERCEL") == "1" or bool(os.getenv("VERCEL_ENV"))
    if is_vercel and not database_url:
        raise RuntimeError("DATABASE_URL must point to a managed PostgreSQL database on Vercel.")

    if database_url:
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as error:
            raise RuntimeError("Install psycopg to use DATABASE_URL.") from error
        connection = psycopg.connect(
            database_url,
            row_factory=dict_row,
            connect_timeout=5,
            sslmode="require",
        )
        try:
            with connection:
                yield _ConnectionAdapter(connection, postgres=True)
        finally:
            connection.close()
        return

    AUTH_DATABASE_PATH.parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(AUTH_DATABASE_PATH, timeout=10)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA foreign_keys = ON")
    try:
        with connection:
            yield _ConnectionAdapter(connection, postgres=False)
    finally:
        connection.close()


def _digest(token: str) -> str:
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def normalize_email(email: str) -> str:
    return email.strip().casefold()


def initialize_auth_database() -> None:
    with _connection() as connection:
        id_type = (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if connection.is_postgres
            else "INTEGER PRIMARY KEY AUTOINCREMENT"
        )
        real_type = "DOUBLE PRECISION" if connection.is_postgres else "REAL"
        statements = (
            f"CREATE TABLE IF NOT EXISTS users ("
            f"id {id_type}, full_name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, "
            f"password_hash TEXT NOT NULL, is_active INTEGER NOT NULL DEFAULT 1, "
            f"created_at {real_type} NOT NULL)",
            f"CREATE TABLE IF NOT EXISTS auth_sessions ("
            f"token_hash TEXT PRIMARY KEY, csrf_hash TEXT NOT NULL, "
            f"user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, "
            f"created_at {real_type} NOT NULL, expires_at {real_type} NOT NULL)",
            f"CREATE TABLE IF NOT EXISTS password_reset_tokens ("
            f"token_hash TEXT PRIMARY KEY, "
            f"user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, "
            f"created_at {real_type} NOT NULL, expires_at {real_type} NOT NULL, "
            f"used_at {real_type})",
            f"CREATE TABLE IF NOT EXISTS oauth_states ("
            f"state_hash TEXT PRIMARY KEY, "
            f"user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, "
            f"created_at {real_type} NOT NULL, expires_at {real_type} NOT NULL)",
            f"CREATE TABLE IF NOT EXISTS gmail_credentials ("
            f"user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE, "
            f"credential_ciphertext TEXT NOT NULL, updated_at {real_type} NOT NULL)",
            f"CREATE TABLE IF NOT EXISTS pending_email_drafts ("
            f"draft_hash TEXT PRIMARY KEY, "
            f"user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, "
            f"recipient TEXT, subject TEXT, body TEXT, draft_ciphertext TEXT, "
            f"expires_at {real_type} NOT NULL)",
            "CREATE INDEX IF NOT EXISTS ix_auth_sessions_user_id ON auth_sessions(user_id)",
            "CREATE INDEX IF NOT EXISTS ix_auth_sessions_expires_at ON auth_sessions(expires_at)",
            "CREATE INDEX IF NOT EXISTS ix_password_reset_user_id ON password_reset_tokens(user_id)",
            "CREATE INDEX IF NOT EXISTS ix_pending_drafts_user_id ON pending_email_drafts(user_id)",
        )
        for statement in statements:
            connection.execute(statement)
        now = time.time()
        connection.execute("DELETE FROM auth_sessions WHERE expires_at <= ?", (now,))
        connection.execute(
            "DELETE FROM password_reset_tokens WHERE expires_at <= ? OR used_at IS NOT NULL",
            (now,),
        )


def create_user(full_name: str, email: str, password_hash: str) -> dict[str, object]:
    with _connection() as connection:
        insert_sql = (
            "INSERT INTO users (full_name, email, password_hash, created_at) "
            "VALUES (?, ?, ?, ?)"
        )
        if connection.is_postgres:
            inserted_user = connection.execute(
                f"{insert_sql} RETURNING id",
                (full_name.strip(), normalize_email(email), password_hash, time.time()),
            ).fetchone()
            user_id = int(inserted_user["id"])
        else:
            cursor = connection.execute(
                insert_sql,
                (full_name.strip(), normalize_email(email), password_hash, time.time()),
            )
            user_id = int(cursor.lastrowid)
        return {
            "id": user_id,
            "full_name": full_name.strip(),
            "email": normalize_email(email),
        }


def get_user_by_email(email: str) -> dict[str, object] | None:
    with _connection() as connection:
        row = connection.execute(
            "SELECT id, full_name, email, password_hash, is_active FROM users WHERE email = ?",
            (normalize_email(email),),
        ).fetchone()
    return dict(row) if row else None


def create_session(user_id: int) -> tuple[str, str]:
    session_token = secrets.token_urlsafe(32)
    csrf_token = secrets.token_urlsafe(32)
    now = time.time()
    with _connection() as connection:
        connection.execute(
            "INSERT INTO auth_sessions (token_hash, csrf_hash, user_id, created_at, expires_at) "
            "VALUES (?, ?, ?, ?, ?)",
            (
                _digest(session_token),
                _digest(csrf_token),
                user_id,
                now,
                now + SESSION_TTL_SECONDS,
            ),
        )
    return session_token, csrf_token


def get_session(session_token: str) -> dict[str, object] | None:
    with _connection() as connection:
        row = connection.execute(
            """
            SELECT sessions.csrf_hash, users.id, users.full_name, users.email, users.is_active
            FROM auth_sessions AS sessions
            JOIN users ON users.id = sessions.user_id
            WHERE sessions.token_hash = ? AND sessions.expires_at > ?
            """,
            (_digest(session_token), time.time()),
        ).fetchone()
    if not row or not row["is_active"]:
        return None
    return dict(row)


def revoke_session(session_token: str) -> None:
    with _connection() as connection:
        connection.execute(
            "DELETE FROM auth_sessions WHERE token_hash = ?", (_digest(session_token),)
        )


def create_password_reset_token(user_id: int) -> str:
    token = secrets.token_urlsafe(32)
    now = time.time()
    with _connection() as connection:
        connection.execute(
            "DELETE FROM password_reset_tokens WHERE user_id = ?", (user_id,)
        )
        connection.execute(
            """
            INSERT INTO password_reset_tokens (token_hash, user_id, created_at, expires_at)
            VALUES (?, ?, ?, ?)
            """,
            (_digest(token), user_id, now, now + PASSWORD_RESET_TTL_SECONDS),
        )
    return token


def delete_password_reset_token(token: str) -> None:
    with _connection() as connection:
        connection.execute(
            "DELETE FROM password_reset_tokens WHERE token_hash = ?", (_digest(token),)
        )


def reset_password(token: str, password_hash: str) -> bool:
    now = time.time()
    with _connection() as connection:
        row = connection.execute(
            """
            SELECT user_id FROM password_reset_tokens
            WHERE token_hash = ? AND expires_at > ? AND used_at IS NULL
            """,
            (_digest(token), now),
        ).fetchone()
        if not row:
            return False

        user_id = row["user_id"]
        connection.execute(
            "UPDATE users SET password_hash = ? WHERE id = ?",
            (password_hash, user_id),
        )
        connection.execute(
            "UPDATE password_reset_tokens SET used_at = ? WHERE token_hash = ?",
            (now, _digest(token)),
        )
        connection.execute("DELETE FROM auth_sessions WHERE user_id = ?", (user_id,))
    return True


def is_duplicate_email_error(error: Exception) -> bool:
    if isinstance(error, sqlite3.IntegrityError):
        return True
    try:
        import psycopg
    except ImportError:
        return False
    return isinstance(error, psycopg.errors.UniqueViolation)


def create_oauth_state(user_id: int) -> str:
    state = secrets.token_urlsafe(32)
    now = time.time()
    with _connection() as connection:
        connection.execute("DELETE FROM oauth_states WHERE expires_at <= ?", (now,))
        connection.execute(
            "INSERT INTO oauth_states (state_hash, user_id, created_at, expires_at) "
            "VALUES (?, ?, ?, ?)",
            (_digest(state), user_id, now, now + OAUTH_STATE_TTL_SECONDS),
        )
    return state


def consume_oauth_state(state: str) -> int | None:
    with _connection() as connection:
        row = connection.execute(
            "DELETE FROM oauth_states WHERE state_hash = ? AND expires_at > ? "
            "RETURNING user_id",
            (_digest(state), time.time()),
        ).fetchone()
    return int(row["user_id"]) if row else None


def store_gmail_credentials(user_id: int, credential_ciphertext: str) -> None:
    with _connection() as connection:
        connection.execute(
            "INSERT INTO gmail_credentials (user_id, credential_ciphertext, updated_at) "
            "VALUES (?, ?, ?) ON CONFLICT(user_id) DO UPDATE SET "
            "credential_ciphertext = excluded.credential_ciphertext, "
            "updated_at = excluded.updated_at",
            (user_id, credential_ciphertext, time.time()),
        )


def get_gmail_credentials(user_id: int) -> str | None:
    with _connection() as connection:
        row = connection.execute(
            "SELECT credential_ciphertext FROM gmail_credentials WHERE user_id = ?",
            (user_id,),
        ).fetchone()
    return str(row["credential_ciphertext"]) if row else None


def delete_gmail_credentials(user_id: int) -> None:
    with _connection() as connection:
        connection.execute("DELETE FROM gmail_credentials WHERE user_id = ?", (user_id,))


def store_pending_email_draft(
    user_id: int,
    draft_id: str,
    recipient: str,
    subject: str,
    body: str,
) -> None:
    now = time.time()
    ciphertext = None
    if os.getenv("VERCEL") == "1":
        from gmail_oauth import encrypt_credentials

        ciphertext = encrypt_credentials(
            json.dumps(
                {"to": recipient, "subject": subject, "body": body},
                ensure_ascii=False,
            )
        )
        recipient = subject = body = ""
    with _connection() as connection:
        connection.execute("DELETE FROM pending_email_drafts WHERE expires_at <= ?", (now,))
        connection.execute(
            "INSERT INTO pending_email_drafts "
            "(draft_hash, user_id, recipient, subject, body, draft_ciphertext, expires_at) "
            "VALUES (?, ?, ?, ?, ?, ?, ?)",
            (
                _digest(draft_id),
                user_id,
                recipient,
                subject,
                body,
                ciphertext,
                now + EMAIL_DRAFT_TTL_SECONDS,
            ),
        )


def consume_pending_email_draft(user_id: int, draft_id: str) -> dict[str, str] | None:
    with _connection() as connection:
        row = connection.execute(
            "DELETE FROM pending_email_drafts "
            "WHERE draft_hash = ? AND user_id = ? AND expires_at > ? "
            "RETURNING recipient, subject, body, draft_ciphertext",
            (_digest(draft_id), user_id, time.time()),
        ).fetchone()
    if not row:
        return None
    if row["draft_ciphertext"]:
        from gmail_oauth import decrypt_credentials

        try:
            draft = json.loads(decrypt_credentials(str(row["draft_ciphertext"])))
        except (TypeError, ValueError):
            return None
        if not isinstance(draft, dict):
            return None
        return {
            "to": str(draft.get("to", "")),
            "subject": str(draft.get("subject", "")),
            "body": str(draft.get("body", "")),
        }
    return {
        "to": str(row["recipient"]),
        "subject": str(row["subject"]),
        "body": str(row["body"]),
    }


def cancel_pending_email_draft(user_id: int, draft_id: str) -> bool:
    with _connection() as connection:
        cursor = connection.execute(
            "DELETE FROM pending_email_drafts WHERE draft_hash = ? AND user_id = ?",
            (_digest(draft_id), user_id),
        )
    return cursor.rowcount > 0
